### ISSUE TITLE
Spread operator in test-support causes

### ISSUE THREAD

**Issue by manuelmitasch** [Deveo/ember-drag-sort#1]
I just installed 1.0.0-alpha.9 of this package using ember cli 2.13.1.
The spread operator used in test-support/pages/components/_components.js produces an error when calling `ember serve`.

```
Livereload server on http://localhost:49153
File: my-app/tests/pages/components/_component.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
SyntaxError: my-app/tests/pages/components/_component.js: Unexpected token (37:4)
  35 | 
  36 |   return {
> 37 |     ...(scope ? { scope, itemScope : scope } : {}), // inject the scope only if it was provided
     |     ^
```

**Comment by lolmaus** [comment]
Hey @manuelmitasch, try installing and enabling the rest-spread transfrom.

```
npm i -D babel-plugin-transform-object-rest-spread
```

```js
// ember-cli-build.js

var app = new EmberApp({
  babel: {
    plugins: [
      'transform-object-rest-spread'
    ]
  }
});
```

**Comment by lolmaus** [comment]
@manuelmitasch Did you manage to resolve this issue?

**Comment by manuelmitasch** [comment]
@lolmaus Thank you for taking time to respond. I just left the issue to notify you about the problem. 
As I needed a quick solution I ended up implemented my own sorting logic based on the ember-drag-drop plugin.
