### ISSUE TITLE
item is not getting dragged to another position

### ISSUE THREAD

**Issue by qwerty-1** [Deveo/ember-drag-sort#15]
After dragging the item to another position it is throwing this error>>>>
 
> The result of a server query (for all globalvariable types) is immutable. To modify contents, use toArray()

how to resolve this error???

my code>>

```hbs
{{#drag-sort-list items=elementdetail dragEndAction = (action 'dragEnd') as |test index|}}         
  {{test.name}}                  
{{/drag-sort-list}}  
```

```js
{
    dragEnd: function({sourceList, sourceIndex, targetList, targetIndex}) {
      if (sourceList === targetList && sourceIndex === targetIndex) return
      const item = sourceList.objectAt(sourceIndex)
      sourceList.removeAt(sourceIndex)
      targetList.insertAt(targetIndex, item)
    },
}
```

**Comment by lolmaus** [comment]
Quoting the very beginning of the readme:

> If you're having trouble using this addon in your project, **please file a properly structured question at [StackOverflow](http://stackoverflow.com/questions/ask?tags=ember.js,ember-drag-sort)**. It is important that you use `ember.js` and `ember-drag-sort` tags for your question to be seen.

This issue queue is for bug reports and feature requests. Please post your question on StackOverflow. I'm receiving notifications for questions tagged with `ember-drag-sort`.
