### ISSUE TITLE
DragImage Lingers After Dropping Item

### ISSUE THREAD

**Issue by livfwd** [Deveo/ember-drag-sort#16]
@lolmaus `ember-drag-sort` is working wonderfully for our needs! We're running into one _small_ issue.

When dragging an item and releasing it, the dragImage seems to fade and drop off of the screen instead of just disappearing immediately.

Video of this behavior > https://cl.ly/o0l4

We get the same behavior here https://deveo.github.io/ember-drag-sort/ as well.

Any idea of what could be causing this and how we can make it stop?

**Comment by lolmaus** [comment]
Hey, @livfwd.

Unlike `jquery-ui-sortable`, `ember-drag-sort` does not control the ghost item. The browser is responsible for it entirely.

Which browser do you see this behavior in?

Not sure if we should keep this issue open. Hypothetically, there may be some browser API to control this behavior, but I'm not gonna research it further. I'll gladly accept a PR though.

**Comment by livfwd** [comment]
@lolmaus - Thanks for the quick response! I have two teammates who see this behavior in both Chrome & Safari on Mac, but I don't think there's any reason to mark this as a bug if it's not an `ember-drag-sort` issue.

**Comment by mikerhyssm** [comment]
Hi @livfwd  did you manage to find a way around this behaviour ?

**Comment by livfwd** [comment]
@mikerhyssm - no, we decided to drop it after learning that it was a browser-based behavior. I was never able to reproduce it.  One of my teammates repro’d it a few times, but can’t anymore, and I think it’s still happening 100% of the time for another teammate. All three of us are on Macs using Chrome.

**Comment by rwwagner90** [comment]
@livfwd how did you get such a nice placeholder line? I've been trying to style the placeholder as a line and I get all kinds of jumpy behavior.

**Comment by rwwagner90** [comment]
PS this issue seems to be the same one I reported here https://github.com/kaliber5/ember-drag-sort/issues/32#issuecomment-560422939

It should be fixed by some `preventDefault`s added in #30

**Comment by lolmaus** [comment]
Fixed in `2.0.0-beta.1`.
