### ISSUE TITLE
ember-drag-sort broken in Firefox prior to Quantum

### ISSUE THREAD

**Issue by livfwd** [Deveo/ember-drag-sort#17]
It does not look like ember-drag-sort supports older versions of Firefox.

This is with 55.0.3 > https://cl.ly/2D0a300x2D2i

**Comment by lolmaus** [comment]
I tried reproducing the issue in BrowserStack and failed. Tried Firefox 55 and 54 on WIndows 10.

Though there's an error visible in the console: `Permission denied to access property "type"`, originating from jQuery, sorting works correctly from the user perspective.

To further investigate this issue, I need a way to reproduce it. Please try reproducing it on BrowserStack.

**Comment by livfwd** [comment]
@lolmaus I am unable to reproduce this issue in BrowserStack.
