### ISSUE TITLE
Better access to the drag event

### ISSUE THREAD

**Issue by RedBird1** [Deveo/ember-drag-sort#23]
This may or may not be an issue. I could be looking in the wrong places. I'm trying to set a custom ghost image to the drag. Also I would like to change the data text in the dragged item. I can't seem to get access to the even to set the image or text. I'm using the evented api to listen to the service for the dragStart, but I have not figured out how to add custom things to the event.

**Comment by vvainio** [comment]
Unfortunately, it's not possible to pass-in custom event handlers through properties, however you can implement this functionality by extending the component. The text and image are controlled in the `drag-sort-item` component's `dragStart` [event handler](https://github.com/Deveo/ember-drag-sort/blob/8a4f0f998c067fa2796914741bfcf57a11c5ab70/addon/components/drag-sort-item.js#L121-L124). To override this functionality, simply create a new component in your app with the same name and extend the addon's component:
```javascript
import dragSortItem from 'ember-drag-sort/components/drag-sort-item'

export default dragSortItem.extend({
  // Copy-paste the `dragStart` function from the addon and modify it as needed.
  // The text and image are controlled in the `event.dataTransfer` if clause below.
  dragStart(event) {
    // Ignore irrelevant drags
    if (!this.get('draggingEnabled')) return

    if (!this.isHandleUsed(event.target)) {
      event.preventDefault()
      return
    }

    event.stopPropagation()

    // Required for Firefox. http://stackoverflow.com/a/32592759/901944
    if (event.dataTransfer) {
      const img = document.createElement('img')
      img.src = '/assets/your-custom-image.png'
      if (event.dataTransfer.setData) event.dataTransfer.setData('text', 'your-custom-text')
      if (event.dataTransfer.setDragImage) event.dataTransfer.setDragImage(img, 0, 0)
    }

    this.startDragging(event)
  }
})
```
Hope this helps! See this blog post on how to customize the "ghost image": https://kryogenix.org/code/browser/custom-drag-image.html

**Comment by RedBird1** [comment]
This solution worked very well for me. I implemented a drag-sort-item-custom and a drag-sort-list-custom component extending the addons. Thank you for the direction.
