### ISSUE TITLE
Access to targetList Group

### ISSUE THREAD

**Issue by RedBird1** [Deveo/ember-drag-sort#24]
Access to the targetList Group..

I have four lists sourceList - and  A - B - C

if my item is dragged to A I wan't to set it's name attr to 'A'
if my item is dragged to B I wan't to set it's name attr to 'B'
if my item is dragged to C I wan't to set it's name attr to 'C'

**Comment by lolmaus** [comment]
If you provide different `group` names to your lists, you won't be able to drag between them. They must all share the same `group`.

You can distinguish by looking at the `{targetList}` argument in the action.

Additionally, you can provide custom arguments to your actions like this:

```handlebars
{{#drag-sort-list
  items         = items1
  dragEndAction = (action 'dragEnd' 'foo')
  as |item|
}}
  {{item.name}}
{{/drag-sort-list}}

{{#drag-sort-list
  items         = items1
  dragEndAction = (action 'dragEnd' 'bar')
  as |item|
}}
  {{item.name}}
{{/drag-sort-list}}
```

Then in the action definition you can accept the custom name like this:

```js
  actions: {
    dragEndAction (customName, {sourceList, sourceIndex, targetList, targetIndex}) {
      customName; // 'foo' or 'bar'
    },
  },
```

I'm closing this ticket for now, but feel free to respond. I'll keep answering. If you demonstrate a bug, I'll reopen the ticket.

PS This is one of the first things mentioned in the readme:

> If you're having trouble using this addon in your project, **please file a properly structured question at [StackOverflow](http://stackoverflow.com/questions/ask?tags=ember.js,ember-drag-sort)**. It is important that you use `ember.js` and `ember-drag-sort` tags for your question to be seen.
