### ISSUE TITLE
Could not find module `ember-awesome-macros/and` imported from `ember-drag-sort/components/drag-sort-list`

### ISSUE THREAD

**Issue by SuperShan0926** [Deveo/ember-drag-sort#3]
how to fix it ? i have already install ember-awesome-macros

**Comment by lolmaus** [comment]
Did you restart the dev server after installing?

**Comment by SuperShan0926** [comment]
i solved, reinstall this package again and it works.perhaps the network problem.thanks anyway.

**Comment by lolmaus** [comment]
Glad you solved it! Don't hesitate to get back to us in case yoy have other issues or questions regarding the addon.

**Comment by SuperShan0926** [comment]
thx a lot bros！
