### ISSUE TITLE
Item jumps to and fro while the mouse pointer is held still

### ISSUE THREAD

**Issue by lolmaus** [Deveo/ember-drag-sort#7]
![adsf](http://i.imgur.com/TQspc2J.gif)

This seems to happen when mouse pointer is positioned near the middle of an item (item height + placeholder padding).

**Comment by lolmaus** [comment]
`$($0).offset()` when the element has no padding: `{top: 241.78125, left: 228}`

`$($0).offset()` when the element has `25px` top padding: `{top: 237.78125, left: 228}`

JQUERY WAT R U DOING AHAHA STAHP!

**Comment by lolmaus** [comment]
Ah, it's because of margin collapsing!

**Comment by livfwd** [comment]
@lolmaus I'm running into the same issue.  Would you mind sharing how you resolved this?
